name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/common-setup

      - name: Install dependencies
        working-directory: frontend
        run: bun install --frozen-lockfile

      - name: Build frontend
        working-directory: frontend
        run: bun run build
